### ISSUE TITLE
How to account for area?

### ISSUE THREAD

**Issue by mirandamanschot** [nikkitissen/DPrepProject#13]

**Comment by Shardahinsenveld** [comment]
First we will look at who adheres to the 30 days rule and who does not and then compare the prices of these houses. After that, as a control variable, we will look at the different neighborhoods in Amsterdam. Wil will compare 'centrum' with 'noord'. While 'centrum' will be the most expensive and 'noord' will be less expensive because it is on the other side of the river.
https://nl.wikipedia.org/wiki/Buurten_en_wijken_in_Amsterdam 
https://allecijfers.nl/gemeente-overzicht/amsterdam/
https://www.amsterdam.nl/buurten/
